version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - binary: stylelintbc
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

# Avoid creating compressed files
archives:
  - format: binary
    name_template: "{{ .Binary }}"

# Specify the main output folder
dist: npm-package/bin

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"